version: '3'
services:
  app:
    build: .
    image: foxyfox/reddit-kopako
    container_name: reddit_container
    ports:
      - "8080:8080"
    environment:
      DB_PREFIX: "jdbc:mysql:"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_NAME: "takeout"
      DB_USERNAME: "kopako"
      DB_PASSWORD: "kopakopass"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_USER: "kopako"
      MYSQL_PASSWORD: "kopakopass"
      MYSQL_DATABASE: "takeout"

